# Generated by Django 4.0.10 on 2023-04-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_patient_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='description',
        ),
    ]
