# Generated by Django 4.0.10 on 2023-04-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_staff_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='staff_id',
            new_name='Staff',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='hod',
            new_name='Head of Department',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='Date of Birth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='NHI',
        ),
    ]
